# Generated by Django 2.2.16 on 2023-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230602_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Лайки у постов'),
        ),
    ]
