# Generated by Django 2.2.16 on 2023-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
